### ISSUE TITLE
Compilation error on openwrt 23.05

### ISSUE THREAD

**Issue by kuncy7** [lmahmutov/SGW-Homeassistant#41]
Hi,
This error occurs when trying to compile on version 23.05:

```rm -f /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built
touch /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built_check
SHELL= flock /home/metium/openwrt/tmp/.pip.flock -c ' ARCH="x86_64" CC="gcc" CCSHARED="gcc -DPIC -fPIC" CXX="g++" LD="gcc" LDSHARED="gcc -shared" CFLAGS="-O2 -I/home/metium/openwrt/staging_dir/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include -I/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include" CPPFLAGS="-I/home/metium/openwrt/staging_dir/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include -I/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include/python3.11" LDFLAGS="-L/home/metium/openwrt/staging_dir/host/lib -L/home/metium/openwrt/staging_dir/hostpkg/lib -L/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/lib -lpython3.11 -Wl,-rpath,/home/metium/openwrt/staging_dir/hostpkg/lib"  CARGO_HOME=/home/metium/openwrt/dl/cargo SETUPTOOLS_RUST_CARGO_PROFILE="release" PIP_CACHE_DIR="/home/metium/openwrt/dl/pip-cache" PIP_CONFIG_FILE=/dev/null PIP_DISABLE_PIP_VERSION_CHECK=1 /home/metium/openwrt/staging_dir/hostpkg/bin/pip3.11 install --no-binary :all: --progress-bar off --require-hashes  --requirement /home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements/ply.txt  ' 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements/ply.txt'
make[3]: *** [Makefile:47: /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built] Error 1
make[3]: Leaving directory '/home/metium/openwrt/feeds/homeassistant/python-packages/python-ha-pycparser'
time: package/feeds/homeassistant/python-ha-pycparser/compile#0.49#0.08#0.56
    ERROR: package/feeds/homeassistant/python-ha-pycparser failed to build.
make[2]: *** [package/Makefile:120: package/feeds/homeassistant/python-ha-pycparser/compile] Error 1
make[2]: Leaving directory '/home/metium/openwrt'
make[1]: *** [package/Makefile:114: /home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/metium/openwrt'
make: *** [/home/metium/openwrt/include/toplevel.mk:232: world] Error 2```

**Comment by lmahmutov** [comment]
23.05 changed logic of python package. I'm working on update

**Comment by kuncy7** [comment]
Hi,
Thank you, I'm waiting for the update.
I wanted to check the current version and compile it in the 22.03 environment, but the compilation also ends with an error:
```
make[3]: Entering directory '/home/metium/openwrt/feeds/homeassistant/python-packages/python-ha-pycparser'
mkdir -p /home/metium/openwrt/dl
SHELL= flock /home/metium/openwrt/tmp/.pycparser-2.21.tar.gz.flock -c '  	/home/metium/openwrt/scripts/download.pl "/home/metium/openwrt/dl" "pycparser-2.21.tar.gz" "e644fdec12f7872f86c58ff790da456218b10f863970249516d60a5eaca77206" "" "https://files.pythonhosted.org/packages/source/p/pycparser"    '
+ curl -f --connect-timeout 20 --retry 5 --location https://files.pythonhosted.org/packages/source/p/pycparser/pycparser-2.21.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  166k  100  166k    0     0   395k      0 --:--:-- --:--:-- --:--:-- 2014k
touch /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.prepared_bb5057478b509cc13056557f90c307ed_6664517399ebbbc92a37c5bb081b5c53_check
. /home/metium/openwrt/include/shell.sh; gzip -dc /home/metium/openwrt/dl/pycparser-2.21.tar.gz | tar -C /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21

Applying ./patches/001-use-external-ply.patch using plaintext: 
patching file pycparser/c_lexer.py
patching file pycparser/c_parser.py
patching file setup.py
touch /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.prepared_bb5057478b509cc13056557f90c307ed_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.configured_*
rm -f /home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.python-ha-pycparser_installed
(cd /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/./; if [ -x ./configure ]; then find /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/ -name config.guess | xargs -r chmod u+w; find /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/ -name config.guess | xargs -r -n1 cp --remove-destination /home/metium/openwrt/scripts/config.guess; find /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/ -name config.sub | xargs -r chmod u+w; find /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/ -name config.sub | xargs -r -n1 cp --remove-destination /home/metium/openwrt/scripts/config.sub; AR="arm-openwrt-linux-muslgnueabi-gcc-ar" AS="arm-openwrt-linux-muslgnueabi-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21=pycparser-2.21 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=arm-openwrt-linux-muslgnueabi-ld NM="arm-openwrt-linux-muslgnueabi-gcc-nm" CC="arm-openwrt-linux-muslgnueabi-gcc" GCC="arm-openwrt-linux-muslgnueabi-gcc" CXX="arm-openwrt-linux-muslgnueabi-g++" RANLIB="arm-openwrt-linux-muslgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-muslgnueabi-strip OBJCOPY=arm-openwrt-linux-muslgnueabi-objcopy OBJDUMP=arm-openwrt-linux-muslgnueabi-objdump SIZE=arm-openwrt-linux-muslgnueabi-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21=pycparser-2.21 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21=pycparser-2.21 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/metium/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.2.0_musl_eabi/usr/include -I/home/metium/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.2.0_musl_eabi/include/fortify -I/home/metium/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.2.0_musl_eabi/include " LDFLAGS="-L/home/metium/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.2.0_musl_eabi/usr/lib -L/home/metium/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.2.0_musl_eabi/lib -znow -zrelro "   ./configure --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  _python_sysroot="/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi" _python_prefix="/usr" _python_exec_prefix="/usr" ; fi; )
if [ -d "/home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements" ] && [ -n "$(find /home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements -maxdepth 1 -mindepth 1 -name '*.txt' -print -quit 2>/dev/null)" ]; then if grep -q "pycparser==" /home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements/*.txt ; then if ! grep -q "pycparser==2.21" /home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements/*.txt ; then printf "\nPlease update version of pycparser to 2.21 in 'host-pip-requirements'/\n\n" ; exit 1 ; fi fi fi
touch /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built
touch /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built_check
SHELL= flock /home/metium/openwrt/tmp/.pip.flock -c ' ARCH="x86_64" CC="gcc" CCSHARED="gcc -DPIC -fPIC" CXX="g++" LD="gcc" LDSHARED="gcc -shared" CFLAGS="-O2 -I/home/metium/openwrt/staging_dir/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include -I/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include" CPPFLAGS="-I/home/metium/openwrt/staging_dir/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include -I/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include -I/home/metium/openwrt/staging_dir/hostpkg/include/python3.10" LDFLAGS="-L/home/metium/openwrt/staging_dir/host/lib -L/home/metium/openwrt/staging_dir/hostpkg/lib -L/home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/lib -lpython3.10 -Wl,-rpath,/home/metium/openwrt/staging_dir/hostpkg/lib" PIP_CACHE_DIR="/home/metium/openwrt/dl/pip-cache" PIP_CONFIG_FILE=/dev/null PIP_DISABLE_PIP_VERSION_CHECK=1 /home/metium/openwrt/staging_dir/hostpkg/bin/pip3.10 install --no-binary :all: --progress-bar off --require-hashes  --requirement /home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements/ply.txt  ' 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/metium/openwrt/feeds/packages/lang/python/host-pip-requirements/ply.txt'
make[3]: *** [Makefile:47: /home/metium/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pypi/pycparser-2.21/.built] Error 1
make[3]: Leaving directory '/home/metium/openwrt/feeds/homeassistant/python-packages/python-ha-pycparser'
time: package/feeds/homeassistant/python-ha-pycparser/compile#0.73#0.15#1.20
    ERROR: package/feeds/homeassistant/python-ha-pycparser failed to build.
make[2]: *** [package/Makefile:120: package/feeds/homeassistant/python-ha-pycparser/compile] Error 1
make[2]: Leaving directory '/home/metium/openwrt'
make[1]: *** [package/Makefile:114: /home/metium/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/metium/openwrt'
make: *** [/home/metium/openwrt/include/toplevel.mk:230: world] Error 2
```
Environment selected with the command: git checkout openwrt-22.03
The first build of the environment completes successfully.
What am I doing wrong this time?
